# Generated by Django 5.2.8 on 2025-11-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_otp_device'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('otp_totp', '0003_add_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_date_jo_ff39bb_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='accounts_us_created_4734df_idx'),
        ),
    ]
