# Generated by Django 5.2.8 on 2025-11-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_usersession_risk_score_user_backup_codes_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usersession',
            name='accounts_us_is_acti_58b48a_idx',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='is_active',
        ),
        migrations.AddField(
            model_name='usersession',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='When this session was revoked (if applicable)', null=True),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['revoked_at'], name='accounts_us_revoked_93d8d3_idx'),
        ),
    ]
